sonar.projectKey=thomasdarmawan9_pnj-logpro-apps
sonar.organization=thomasdarmawan9

sonar.projectName=PNJ LogPro Apps
sonar.sources=app,components,features,lib,store,proxy.ts,pnj-backend/src,pnj-backend/server.js
sonar.exclusions=**/node_modules/**,**/.next/**,**/migrations/**,**/seeders/**,**/uploads/**,**/pdfs/**,**/logs/**,**/*.test.*,**/*.spec.*

sonar.sourceEncoding=UTF-8
