import { SuratJalan, StatusOperasional, StatusLampiran } from '../../features/surat-jalan/domain/entities/SuratJalan'

export const MOCK_SURAT_JALAN: SuratJalan[] = [
  {
    id: 1, uuid: 'sj-001', sj_number: 'SJ-2026-089',
    project_id: 1,
    project: { id: 1, name: 'Proyek Sewa Kendaraan Maret', contract_number: '002/HRD/III/2026', code: 'PRJ-2026-001' },
    customer_id: 1,
    customer: { id: 1, name: 'PT. ATP BIO' },
    fleet_id: 1,
    fleet: { id: 1, name: 'Toyota Zenix', plate_number: 'KB 1561 HX', is_tbd: false },
    driver_id: 1,
    driver: { id: 1, name: 'Budi Santoso', sim_expired_at: '2026-08-15' },
    driver_name_manual: null,
    sj_date: '2026-03-14',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'Lokasi PT. ATP BIO, Kubu Raya',
    cargo_description: 'Kendaraan operasional untuk periode sewa',
    operational_cost: 1500000,
    status: StatusOperasional.DELIVERED,
    invoice_id: 1,
    invoice_attachment_status: StatusLampiran.ATTACHED,
    invoice: { id: 1, invoice_number: '2829' },
    delivered_at: '2026-03-14T14:30:00Z',
    pod_photo_path: '/mock/pod-sj-089.jpg',
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-03-12T08:50:00Z', updated_at: '2026-03-14T14:30:00Z',
  },
  {
    id: 2, uuid: 'sj-002', sj_number: 'SJ-2026-088',
    project_id: 2,
    project: { id: 2, name: 'Logistik Q1 2026', contract_number: '015/LOG/I/2026', code: 'PRJ-2026-002' },
    customer_id: 2,
    customer: { id: 2, name: 'PT. Borneo Maju' },
    fleet_id: 2,
    fleet: { id: 2, name: 'Mitsubishi Colt', plate_number: 'KB 2233 CD', is_tbd: false },
    driver_id: 2,
    driver: { id: 2, name: 'Agus Widodo', sim_expired_at: '2026-04-10' },
    driver_name_manual: null,
    sj_date: '2026-03-13',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'Warehouse PT. Borneo Maju, Sungai Raya',
    cargo_description: 'Barang elektronik — 20 karton',
    operational_cost: 850000,
    status: StatusOperasional.DELIVERED,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: '2026-03-13T16:00:00Z',
    pod_photo_path: '/mock/pod-sj-088.jpg',
    lampiran_paths: null,
    void_reason: null,
    internal_notes: 'Perhatikan kondisi barang elektronik',
    created_by: 1, created_at: '2026-03-11T10:00:00Z', updated_at: '2026-03-13T16:00:00Z',
  },
  {
    id: 3, uuid: 'sj-003', sj_number: 'SJ-2026-087',
    project_id: 1,
    project: { id: 1, name: 'Proyek Sewa Kendaraan Maret', contract_number: '002/HRD/III/2026', code: 'PRJ-2026-001' },
    customer_id: 1,
    customer: { id: 1, name: 'PT. ATP BIO' },
    fleet_id: 3,
    fleet: { id: 3, name: 'Toyota Veloz', plate_number: 'KB 8821 HX', is_tbd: false },
    driver_id: 3,
    driver: { id: 3, name: 'Hendra Kusuma', sim_expired_at: '2027-01-20' },
    driver_name_manual: null,
    sj_date: '2026-03-12',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'Lokasi PT. ATP BIO, Kubu Raya',
    cargo_description: null,
    operational_cost: 1200000,
    status: StatusOperasional.ASSIGNED,
    invoice_id: 1,
    invoice_attachment_status: StatusLampiran.ATTACHED,
    invoice: { id: 1, invoice_number: '2829' },
    delivered_at: null,
    pod_photo_path: null,
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-03-12T09:00:00Z', updated_at: '2026-03-12T09:15:00Z',
  },
  {
    id: 4, uuid: 'sj-004', sj_number: 'SJ-2026-086',
    project_id: 3,
    project: { id: 3, name: 'Kontrak Transportasi Feb', contract_number: '008/KBE/II/2026', code: 'PRJ-2026-003' },
    customer_id: 3,
    customer: { id: 3, name: 'PT. Kalbar Energi' },
    fleet_id: 4,
    fleet: { id: 4, name: 'Daihatsu Gran Max', plate_number: 'KB 4455 AB', is_tbd: false },
    driver_id: 4,
    driver: { id: 4, name: 'Rizki Pratama', sim_expired_at: '2026-03-10' },
    driver_name_manual: null,
    sj_date: '2026-03-11',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'PLTU Kalbar, Kec. Sungai Raya',
    cargo_description: 'Suku cadang mesin — 5 pcs',
    operational_cost: 2100000,
    status: StatusOperasional.DELIVERED,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: '2026-03-11T18:45:00Z',
    pod_photo_path: '/mock/pod-sj-086.jpg',
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-03-09T08:00:00Z', updated_at: '2026-03-11T18:45:00Z',
  },
  {
    id: 5, uuid: 'sj-005', sj_number: 'SJ-2026-085',
    project_id: 4,
    project: { id: 4, name: 'Proyek Alat Berat Q1', contract_number: '021/AB/I/2026', code: 'PRJ-2026-004' },
    customer_id: 4,
    customer: { id: 4, name: 'PT. Sawit Borneo' },
    fleet_id: 5,
    fleet: { id: 5, name: 'Truck Fuso', plate_number: 'KB 9988 ZZ', is_tbd: false },
    driver_id: null,
    driver: null,
    driver_name_manual: 'Sopir Kontrak - Dedi',
    sj_date: '2026-03-10',
    origin: 'Pelabuhan Pontianak',
    destination: 'Kebun Sawit Selatan, Ketapang',
    cargo_description: 'Alat berat — excavator mini',
    operational_cost: 4500000,
    status: StatusOperasional.DELIVERED,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: '2026-03-10T20:00:00Z',
    pod_photo_path: null,
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-03-08T07:00:00Z', updated_at: '2026-03-10T20:00:00Z',
  },
  {
    id: 6, uuid: 'sj-006', sj_number: 'SJ-2026-084',
    project_id: 2,
    project: { id: 2, name: 'Logistik Q1 2026', contract_number: '015/LOG/I/2026', code: 'PRJ-2026-002' },
    customer_id: 2,
    customer: { id: 2, name: 'PT. Borneo Maju' },
    fleet_id: 0,
    fleet: { id: 0, name: 'Belum Ditentukan', plate_number: 'TBD', is_tbd: true },
    driver_id: null,
    driver: null,
    driver_name_manual: null,
    sj_date: '2026-03-15',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'Warehouse PT. Borneo Maju, Sungai Raya',
    cargo_description: null,
    operational_cost: 0,
    status: StatusOperasional.DRAFT,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: null,
    pod_photo_path: null,
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-03-15T08:00:00Z', updated_at: '2026-03-15T08:00:00Z',
  },
  {
    id: 7, uuid: 'sj-007', sj_number: 'SJ-2026-083',
    project_id: 1,
    project: { id: 1, name: 'Proyek Sewa Kendaraan Maret', contract_number: '002/HRD/III/2026', code: 'PRJ-2026-001' },
    customer_id: 1,
    customer: { id: 1, name: 'PT. ATP BIO' },
    fleet_id: 6,
    fleet: { id: 6, name: 'Honda CR-V', plate_number: 'KB 3344 EF', is_tbd: false },
    driver_id: 5,
    driver: { id: 5, name: 'Slamet Riyadi', sim_expired_at: '2028-05-01' },
    driver_name_manual: null,
    sj_date: '2026-03-09',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'Kantor PT. ATP BIO, Pontianak Selatan',
    cargo_description: 'Dokumen dan perlengkapan kantor',
    operational_cost: 300000,
    status: StatusOperasional.DELIVERED,
    invoice_id: 1,
    invoice_attachment_status: StatusLampiran.ATTACHED,
    invoice: { id: 1, invoice_number: '2829' },
    delivered_at: '2026-03-09T11:00:00Z',
    pod_photo_path: '/mock/pod-sj-083.jpg',
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-03-07T08:00:00Z', updated_at: '2026-03-09T11:00:00Z',
  },
  {
    id: 8, uuid: 'sj-008', sj_number: 'SJ-2026-082',
    project_id: 3,
    project: { id: 3, name: 'Kontrak Transportasi Feb', contract_number: '008/KBE/II/2026', code: 'PRJ-2026-003' },
    customer_id: 3,
    customer: { id: 3, name: 'PT. Kalbar Energi' },
    fleet_id: 7,
    fleet: { id: 7, name: 'Toyota Hilux', plate_number: 'KB 7712 GH', is_tbd: false },
    driver_id: 6,
    driver: { id: 6, name: 'Wahyu Pratama', sim_expired_at: '2026-12-31' },
    driver_name_manual: null,
    sj_date: '2026-03-08',
    origin: 'Workshop PNJ, Jl. Tanjung Raya Pontianak',
    destination: 'Substation PLN, Mempawah',
    cargo_description: 'Peralatan instalasi listrik',
    operational_cost: 1800000,
    status: StatusOperasional.ASSIGNED,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: null,
    pod_photo_path: null,
    lampiran_paths: null,
    void_reason: null,
    internal_notes: 'Hati-hati barang fragile',
    created_by: 1, created_at: '2026-03-06T09:00:00Z', updated_at: '2026-03-08T07:30:00Z',
  },
  {
    id: 9, uuid: 'sj-009', sj_number: 'SJ-2026-081',
    project_id: 5,
    project: { id: 5, name: 'Ekspedisi Singkawang', contract_number: '031/EKS/II/2026', code: 'PRJ-2026-005' },
    customer_id: 5,
    customer: { id: 5, name: 'PT. Singkawang Trans' },
    fleet_id: 8,
    fleet: { id: 8, name: 'Isuzu Elf', plate_number: 'KB 5566 IJ', is_tbd: false },
    driver_id: 7,
    driver: { id: 7, name: 'Ahmad Fauzi', sim_expired_at: '2027-03-15' },
    driver_name_manual: null,
    sj_date: '2026-03-07',
    origin: 'Terminal Kargo Pontianak',
    destination: 'Gudang PT. Singkawang Trans',
    cargo_description: 'Sembako — 200 karton',
    operational_cost: 2500000,
    status: StatusOperasional.VOID,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: null,
    pod_photo_path: null,
    lampiran_paths: null,
    void_reason: 'Kendaraan mengalami kerusakan di perjalanan, SJ dibatalkan',
    internal_notes: null,
    created_by: 1, created_at: '2026-03-05T08:00:00Z', updated_at: '2026-03-07T15:00:00Z',
  },
  {
    id: 10, uuid: 'sj-010', sj_number: 'SJ-2026-080',
    project_id: 4,
    project: { id: 4, name: 'Proyek Alat Berat Q1', contract_number: '021/AB/I/2026', code: 'PRJ-2026-004' },
    customer_id: 4,
    customer: { id: 4, name: 'PT. Sawit Borneo' },
    fleet_id: 5,
    fleet: { id: 5, name: 'Truck Fuso', plate_number: 'KB 9988 ZZ', is_tbd: false },
    driver_id: 8,
    driver: { id: 8, name: 'Didik Subagyo', sim_expired_at: '2026-06-30' },
    driver_name_manual: null,
    sj_date: '2026-03-05',
    origin: 'Pelabuhan Pontianak',
    destination: 'Lokasi Tambang, Sanggau',
    cargo_description: 'Mesin pompa air industri',
    operational_cost: 3200000,
    status: StatusOperasional.DELIVERED,
    invoice_id: 2,
    invoice_attachment_status: StatusLampiran.ATTACHED,
    invoice: { id: 2, invoice_number: '2828' },
    delivered_at: '2026-03-05T22:00:00Z',
    pod_photo_path: '/mock/pod-sj-080.jpg',
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-03-03T08:00:00Z', updated_at: '2026-03-05T22:00:00Z',
  },
  {
    id: 11, uuid: 'sj-011', sj_number: 'SJ-2026-079',
    project_id: 2,
    project: { id: 2, name: 'Logistik Q1 2026', contract_number: '015/LOG/I/2026', code: 'PRJ-2026-002' },
    customer_id: 2,
    customer: { id: 2, name: 'PT. Borneo Maju' },
    fleet_id: 2,
    fleet: { id: 2, name: 'Mitsubishi Colt', plate_number: 'KB 2233 CD', is_tbd: false },
    driver_id: 2,
    driver: { id: 2, name: 'Agus Widodo', sim_expired_at: '2026-04-10' },
    driver_name_manual: null,
    sj_date: '2026-03-04',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'Gudang Cabang Sambas',
    cargo_description: 'Bahan bangunan — semen 50 sak',
    operational_cost: 950000,
    status: StatusOperasional.DELIVERED,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: '2026-03-04T17:30:00Z',
    pod_photo_path: '/mock/pod-sj-079.jpg',
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-03-02T08:00:00Z', updated_at: '2026-03-04T17:30:00Z',
  },
  {
    id: 12, uuid: 'sj-012', sj_number: 'SJ-2026-078',
    project_id: 1,
    project: { id: 1, name: 'Proyek Sewa Kendaraan Maret', contract_number: '002/HRD/III/2026', code: 'PRJ-2026-001' },
    customer_id: 1,
    customer: { id: 1, name: 'PT. ATP BIO' },
    fleet_id: 9,
    fleet: { id: 9, name: 'Daihatsu Xenia', plate_number: 'KB 1122 KL', is_tbd: false },
    driver_id: 9,
    driver: { id: 9, name: 'Bambang Irawan', sim_expired_at: '2026-09-20' },
    driver_name_manual: null,
    sj_date: '2026-03-03',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'Pabrik PT. ATP BIO, Kubu Raya',
    cargo_description: null,
    operational_cost: 750000,
    status: StatusOperasional.DRAFT,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: null,
    pod_photo_path: null,
    lampiran_paths: null,
    void_reason: null,
    internal_notes: 'Menunggu konfirmasi jadwal dari customer',
    created_by: 1, created_at: '2026-03-01T14:00:00Z', updated_at: '2026-03-01T14:00:00Z',
  },
  {
    id: 13, uuid: 'sj-013', sj_number: 'SJ-2026-077',
    project_id: 5,
    project: { id: 5, name: 'Ekspedisi Singkawang', contract_number: '031/EKS/II/2026', code: 'PRJ-2026-005' },
    customer_id: 5,
    customer: { id: 5, name: 'PT. Singkawang Trans' },
    fleet_id: 8,
    fleet: { id: 8, name: 'Isuzu Elf', plate_number: 'KB 5566 IJ', is_tbd: false },
    driver_id: 7,
    driver: { id: 7, name: 'Ahmad Fauzi', sim_expired_at: '2027-03-15' },
    driver_name_manual: null,
    sj_date: '2026-02-28',
    origin: 'Terminal Kargo Pontianak',
    destination: 'Gudang PT. Singkawang Trans',
    cargo_description: 'Peralatan rumah tangga',
    operational_cost: 2200000,
    status: StatusOperasional.DELIVERED,
    invoice_id: 3,
    invoice_attachment_status: StatusLampiran.ATTACHED,
    invoice: { id: 3, invoice_number: '2827' },
    delivered_at: '2026-02-28T19:00:00Z',
    pod_photo_path: '/mock/pod-sj-077.jpg',
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-02-26T08:00:00Z', updated_at: '2026-02-28T19:00:00Z',
  },
  {
    id: 14, uuid: 'sj-014', sj_number: 'SJ-2026-076',
    project_id: 3,
    project: { id: 3, name: 'Kontrak Transportasi Feb', contract_number: '008/KBE/II/2026', code: 'PRJ-2026-003' },
    customer_id: 3,
    customer: { id: 3, name: 'PT. Kalbar Energi' },
    fleet_id: 4,
    fleet: { id: 4, name: 'Daihatsu Gran Max', plate_number: 'KB 4455 AB', is_tbd: false },
    driver_id: 10,
    driver: { id: 10, name: 'Ferdi Santoso', sim_expired_at: '2025-12-31' },
    driver_name_manual: null,
    sj_date: '2026-02-25',
    origin: 'Gudang PNJ, Jl. Supadio Pontianak',
    destination: 'Gardu Induk PLN, Sanggau',
    cargo_description: 'Trafo distribusi 250 KVA',
    operational_cost: 3800000,
    status: StatusOperasional.DRAFT,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: null,
    pod_photo_path: null,
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-02-23T09:00:00Z', updated_at: '2026-02-23T09:00:00Z',
  },
  {
    id: 15, uuid: 'sj-015', sj_number: 'SJ-2026-075',
    project_id: 4,
    project: { id: 4, name: 'Proyek Alat Berat Q1', contract_number: '021/AB/I/2026', code: 'PRJ-2026-004' },
    customer_id: 4,
    customer: { id: 4, name: 'PT. Sawit Borneo' },
    fleet_id: 10,
    fleet: { id: 10, name: 'Mitsubishi Fuso Fighter', plate_number: 'KB 8899 MN', is_tbd: false },
    driver_id: null,
    driver: null,
    driver_name_manual: 'Sopir Kontrak - Anton',
    sj_date: '2026-02-20',
    origin: 'Pelabuhan Pontianak',
    destination: 'Kebun Sawit Utara, Ketapang',
    cargo_description: 'Generator set 100 KVA',
    operational_cost: 5500000,
    status: StatusOperasional.DELIVERED,
    invoice_id: null,
    invoice_attachment_status: StatusLampiran.NO_INVOICE,
    invoice: null,
    delivered_at: '2026-02-20T23:00:00Z',
    pod_photo_path: '/mock/pod-sj-075.jpg',
    lampiran_paths: null,
    void_reason: null,
    internal_notes: null,
    created_by: 1, created_at: '2026-02-18T08:00:00Z', updated_at: '2026-02-20T23:00:00Z',
  },
]

export const MOCK_PROJECTS = [
  { id: 1, name: 'Proyek Sewa Kendaraan Maret', contract_number: '002/HRD/III/2026', code: 'PRJ-2026-001', customer: { id: 1, name: 'PT. ATP BIO' } },
  { id: 2, name: 'Logistik Q1 2026', contract_number: '015/LOG/I/2026', code: 'PRJ-2026-002', customer: { id: 2, name: 'PT. Borneo Maju' } },
  { id: 3, name: 'Kontrak Transportasi Feb', contract_number: '008/KBE/II/2026', code: 'PRJ-2026-003', customer: { id: 3, name: 'PT. Kalbar Energi' } },
  { id: 4, name: 'Proyek Alat Berat Q1', contract_number: '021/AB/I/2026', code: 'PRJ-2026-004', customer: { id: 4, name: 'PT. Sawit Borneo' } },
  { id: 5, name: 'Ekspedisi Singkawang', contract_number: '031/EKS/II/2026', code: 'PRJ-2026-005', customer: { id: 5, name: 'PT. Singkawang Trans' } },
]

export const MOCK_FLEETS = [
  { id: 0, name: 'Belum Ditentukan', plate_number: 'TBD', category: '', is_tbd: true, status: 'active' },
  { id: 1, name: 'Toyota Zenix', plate_number: 'KB 1561 HX', category: 'Mobil Keluarga', is_tbd: false, status: 'active' },
  { id: 2, name: 'Mitsubishi Colt', plate_number: 'KB 2233 CD', category: 'Minibus', is_tbd: false, status: 'active' },
  { id: 3, name: 'Toyota Veloz', plate_number: 'KB 8821 HX', category: 'Mobil Keluarga', is_tbd: false, status: 'active' },
  { id: 4, name: 'Daihatsu Gran Max', plate_number: 'KB 4455 AB', category: 'Pickup', is_tbd: false, status: 'active' },
  { id: 5, name: 'Truck Fuso', plate_number: 'KB 9988 ZZ', category: 'Truck Besar', is_tbd: false, status: 'active' },
  { id: 6, name: 'Honda CR-V', plate_number: 'KB 3344 EF', category: 'SUV', is_tbd: false, status: 'active' },
  { id: 7, name: 'Toyota Hilux', plate_number: 'KB 7712 GH', category: 'Pickup', is_tbd: false, status: 'active' },
  { id: 8, name: 'Isuzu Elf', plate_number: 'KB 5566 IJ', category: 'Minibus', is_tbd: false, status: 'active' },
  { id: 9, name: 'Daihatsu Xenia', plate_number: 'KB 1122 KL', category: 'Mobil Keluarga', is_tbd: false, status: 'active' },
  { id: 10, name: 'Mitsubishi Fuso Fighter', plate_number: 'KB 8899 MN', category: 'Truck Besar', is_tbd: false, status: 'active' },
]

export const MOCK_DRIVERS = [
  { id: 1, name: 'Budi Santoso', sim_number: 'A-123456', sim_expired_at: '2026-08-15', status: 'active' },
  { id: 2, name: 'Agus Widodo', sim_number: 'B-234567', sim_expired_at: '2026-04-10', status: 'active' },
  { id: 3, name: 'Hendra Kusuma', sim_number: 'A-345678', sim_expired_at: '2027-01-20', status: 'active' },
  { id: 4, name: 'Rizki Pratama', sim_number: 'B-456789', sim_expired_at: '2026-03-10', status: 'active' },
  { id: 5, name: 'Slamet Riyadi', sim_number: 'A-567890', sim_expired_at: '2028-05-01', status: 'active' },
  { id: 6, name: 'Wahyu Pratama', sim_number: 'B-678901', sim_expired_at: '2026-12-31', status: 'active' },
  { id: 7, name: 'Ahmad Fauzi', sim_number: 'A-789012', sim_expired_at: '2027-03-15', status: 'active' },
  { id: 8, name: 'Didik Subagyo', sim_number: 'B-890123', sim_expired_at: '2026-06-30', status: 'active' },
  { id: 9, name: 'Bambang Irawan', sim_number: 'A-901234', sim_expired_at: '2026-09-20', status: 'active' },
  { id: 10, name: 'Ferdi Santoso', sim_number: 'B-012345', sim_expired_at: '2025-12-31', status: 'active' },
]
